CREATE TYPE "TransactionStatus" AS ENUM (
  'Pending',
  'Completed',
  'Failed'
);

CREATE TYPE "BookingStatus" AS ENUM (
  'Confirmed',
  'PendingDeposit',
  'InProgress',
  'PendingPayment',
  'Completed',
  'Canceled'
);

CREATE TYPE "FuelType" AS ENUM (
  'Gasoline',
  'Diesel'
);

CREATE TYPE "CarColor" AS ENUM (
  'Blue',
  'Green'
);

CREATE TYPE "TransmissionType" AS ENUM (
  'Manual',
  'Automatic'
);

CREATE TYPE "TransactionType" AS ENUM (
  'Topup',
  'Withdraw'
);

CREATE TYPE "UserRole" AS ENUM (
  'Customer',
  'CarOwner'
);

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar,
  "driver_license" varchar,
  "dob" TIMESTAMP,
  "provider" varchar(50),
  "provider_id" varchar(255),
  "access_token" varchar(255),
  "refresh_token" varchar(255),
  "role_id" int
);

CREATE TABLE "UserAddress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "house_address" varchar,
  "ward" varchar,
  "district" varchar,
  "city" varchar
);

CREATE TABLE "Role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" "UserRole" NOT NULL
);

CREATE TABLE "Feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" int UNIQUE,
  "rating" int,
  "comment" text
);

CREATE TABLE "Booking" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "car_id" int,
  "booking_number" varchar UNIQUE NOT NULL,
  "start_date_time" timestamp NOT NULL,
  "end_date_time" timestamp NOT NULL,
  "status" "BookingStatus"
);

CREATE TABLE "Wallet" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int UNIQUE,
  "balance" decimal(15,3)
);

CREATE TABLE "Transaction" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wallet_id" int,
  "amount" decimal(15,3) NOT NULL,
  "transaction_date" timestamp,
  "type" "TransactionType",
  "transaction_id" varchar,
  "status" "TransactionStatus"
);

CREATE TABLE "Car" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" int,
  "name" varchar NOT NULL,
  "license_plate" varchar UNIQUE NOT NULL,
  "brand" varchar,
  "model" varchar,
  "color" varchar,
  "seat_quantity" int,
  "production_year" int,
  "transmission_type" "TransmissionType",
  "fuel_type" "FuelType",
  "registration_paper" varchar,
  "inspection_certificate" varchar,
  "insurance" varchar,
  "description" text,
  "fuel_consumption" varchar,
  "deposit" decimal(15,3) NOT NULL,
  "baseprice" decimal(15,3) NOT NULL,
  "custom_terms" text DEFAULT ''
);

CREATE TABLE "CarImage" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" int,
  "path" varchar,
  "alt" varchar
);

CREATE TABLE "CarAddress" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" int UNIQUE,
  "house_address" varchar,
  "ward" varchar,
  "district" varchar,
  "city" varchar
);

CREATE TABLE "AdditionalFeature" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text DEFAULT ''
);

CREATE TABLE "CarFeature" (
  "car_id" int,
  "feature_id" int,
  PRIMARY KEY ("car_id", "feature_id")
);

CREATE TABLE "Term" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text DEFAULT ''
);

CREATE TABLE "CarTerm" (
  "car_id" int,
  "term_id" int,
  PRIMARY KEY ("car_id", "term_id")
);

COMMENT ON TABLE "UserAddress" IS 'one-to-one relationship';

COMMENT ON COLUMN "UserAddress"."ward" IS 'Xã';

COMMENT ON TABLE "Feedback" IS 'one-to-one relationship';

COMMENT ON COLUMN "Feedback"."rating" IS 'Rating from 1 to 5';

COMMENT ON TABLE "Wallet" IS 'One-to-one relationship';

COMMENT ON TABLE "CarAddress" IS 'One-to-One relationship';

ALTER TABLE "UserAddress" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "User" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id");

ALTER TABLE "Wallet" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

ALTER TABLE "Transaction" ADD FOREIGN KEY ("wallet_id") REFERENCES "Wallet" ("id");

ALTER TABLE "CarImage" ADD FOREIGN KEY ("car_id") REFERENCES "Car" ("id");

ALTER TABLE "CarAddress" ADD FOREIGN KEY ("car_id") REFERENCES "Car" ("id");

ALTER TABLE "CarFeature" ADD FOREIGN KEY ("feature_id") REFERENCES "AdditionalFeature" ("id");

ALTER TABLE "CarFeature" ADD FOREIGN KEY ("car_id") REFERENCES "Car" ("id");

ALTER TABLE "CarTerm" ADD FOREIGN KEY ("car_id") REFERENCES "Car" ("id");

ALTER TABLE "CarTerm" ADD FOREIGN KEY ("term_id") REFERENCES "Term" ("id");

ALTER TABLE "Feedback" ADD FOREIGN KEY ("booking_id") REFERENCES "Booking" ("id");

ALTER TABLE "Car" ADD FOREIGN KEY ("owner_id") REFERENCES "User" ("id");

ALTER TABLE "Booking" ADD FOREIGN KEY ("car_id") REFERENCES "Car" ("id");

ALTER TABLE "Booking" ADD FOREIGN KEY ("customer_id") REFERENCES "User" ("id");
